services:
  desafio-app:
    build:
      context: .
      dockerfile: .docker/dev/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: desafio_app
    volumes:
      - ./:/var/www
    depends_on:
      - desafio-db
      - desafio-redis

  desafio-nginx:
    image: nginx:alpine
    container_name: desafio_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./.docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - desafio-app

  desafio-db:
    image: mysql:8.4
    container_name: desafio_db
    environment:
      MYSQL_DATABASE: desafio_meli
      MYSQL_USER: desafio_meli
      MYSQL_PASSWORD: desafio_meli
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - desafio_db_data:/var/lib/mysql

  desafio-redis:
    image: redis:alpine
    container_name: desafio_redis

  desafio-mockoon:
    image: mockoon/cli:latest
    container_name: desafio_mockoon
    command: ["-d", "/data/meli-mockoon.json", "-p", "3001"]
    ports:
      - "3001:3001"
    volumes:
      - ./.docker/dev/mockoon/meli-mockoon.json:/data/meli-mockoon.json:ro

volumes:
  desafio_db_data:
